server.port: 8006
spring:
   kafka:
      consumer:
         bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
         group-id: group1
         auto-offset-reset: earliest
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: com.example.demo.serializer.LocationDeserializer
         fetch-min-size: 16384
         max-poll-records: 20
         listener:
            type: batch
      producer:
         bootstrap-servers: localhost:9092
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: com.example.demo.serializer.LocationSerializer
         compression-type: zstd
         batch-size: 32768
         properties:  
            linger.ms: 20
   datasource:
      url: jdbc:h2:mem:mydb
      driverClassName: org.h2.Driver
      username: sa
      password:
      schema: classpath:/schema.sql
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
   h2:
      console.enabled: true   